### ISSUE TITLE
Webservice [Frontend] - Tela de Interface com o usuário

### ISSUE THREAD

**Issue by helam01** [ferauche/RoboAlegria#16]
Desenvolver a tela de Interface, que enviará os dados para o backend.  
A Interface deve ser baseada na imagem abaixo.  
![alt tag](https://raw.githubusercontent.com/helam01/RoboAlegria/webservice/images/interface_web.jpg)

**Comment by ferauche** [comment]
@igorfonseca83 poderia mandar um pullrequest com o código da página que contém a interface, e o código usando JQUERY para mandar os requests ao webservice?
