### ISSUE TITLE
Desenhar um esquema elétrico de ligação com o Arduino

### ISSUE THREAD

**Issue by ferauche** [ferauche/RoboAlegria#9]
Desenhar no Fritzing (http://fritzing.org) o esquemático com as ligações com as matrizes de Leds, o módulo HC-06 e os servos (com alimentação separada)

**Comment by igorfonseca83** [comment]
![robot mk0_bb](https://cloud.githubusercontent.com/assets/18287667/14768930/013e02d0-0a24-11e6-96e4-ad4b586fff65.png)

**Comment by ferauche** [comment]
Show, obrigado Igor!

**Comment by igorfonseca83** [comment]
Estou trabalhando na PCB para fazermos a primeira versão de um shield.
Assim que estiver pronto eu compartilho.
Em 25 de abr de 2016 4:45 PM, "Thiago Ferauche" notifications@github.com
escreveu:
